name: emonitor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  auto_size_text: ^3.0.0
  build_runner: ^2.4.14
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_bakong_khqr: ^0.0.1+3
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  path_provider: ^2.1.5
  percent_indicator: ^4.2.4
  pie_chart: ^5.4.0
  provider: ^6.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/